import '../globals.css'

export const metadata = {
  title: 'Deaa Aldin Alawad',
  description: 'Generated by Deaa Aldin Alawad',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
